[package]
name = "podtracker"
version = "0.1.0"
edition = "2021"

[dependencies]
docker-api = "0.8.0"
anyhow = "1"
serde = "1"
tokio = { version = "1", features = ["full"] }
rocket = "0.5.0-rc.1"
clap = { version = "3.1.3", features = ["derive"] }
