[package]
description = "Framework to help developing phala sidevm program"
license = "Apache-2.0"
homepage = "https://github.com/Phala-Network/phala-blockchain"
edition = "2021"
name = "pink-sidevm"
version = "0.1.1"

[dependencies]
pink-sidevm-env = {version = "0.1.1", path = "../env"}
pink-sidevm-logger = {version = "0.1.0", path = "../logger"}
pink-sidevm-macro = {version = "0.1.0", path = "../macro"}
log = "0.4.16"

hyper = {version = "0.14.18", features = ["server"], optional = true}
tokio = {version = "1", optional = true}
futures = {version = "0.3", optional = true}

[features]
default = ["hyper", "tokio", "futures"]
